/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface OnChainPixelArtv2Interface extends ethers.utils.Interface {
  functions: {
    "base64Encode(bytes)": FunctionFragment;
    "composeLayers(uint256[],uint256[],uint256)": FunctionFragment;
    "composePalettes(uint256[],uint256[],uint256,uint256)": FunctionFragment;
    "encodeColorArray(uint256[],uint256,uint256)": FunctionFragment;
    "getColorCount(uint256[])": FunctionFragment;
    "render(uint256[],uint256[],uint256,uint256,string,uint256,uint256)": FunctionFragment;
    "toHexString(uint256)": FunctionFragment;
    "toString(uint256)": FunctionFragment;
    "uri(string)": FunctionFragment;
    "uriSvg(string)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "base64Encode",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "composeLayers",
    values: [BigNumberish[], BigNumberish[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "composePalettes",
    values: [BigNumberish[], BigNumberish[], BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "encodeColorArray",
    values: [BigNumberish[], BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getColorCount",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "render",
    values: [
      BigNumberish[],
      BigNumberish[],
      BigNumberish,
      BigNumberish,
      string,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "toHexString",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "toString",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "uri", values: [string]): string;
  encodeFunctionData(functionFragment: "uriSvg", values: [string]): string;

  decodeFunctionResult(
    functionFragment: "base64Encode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "composeLayers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "composePalettes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "encodeColorArray",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getColorCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "render", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "toHexString",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "toString", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "uri", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "uriSvg", data: BytesLike): Result;

  events: {};
}

export class OnChainPixelArtv2 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: OnChainPixelArtv2Interface;

  functions: {
    base64Encode(data: BytesLike, overrides?: CallOverrides): Promise<[string]>;

    composeLayers(
      layer1: BigNumberish[],
      layer2: BigNumberish[],
      totalPixels: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber[]] & { comp: BigNumber[] }>;

    composePalettes(
      palette1: BigNumberish[],
      palette2: BigNumberish[],
      colorCount1: BigNumberish,
      colorCount2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber[]] & { composedPalette: BigNumber[] }>;

    encodeColorArray(
      colors: BigNumberish[],
      pixelCompression: BigNumberish,
      colorCount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber[]] & { encoded: BigNumber[] }>;

    getColorCount(
      layers: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { colorCount: BigNumber }>;

    render(
      canvas: BigNumberish[],
      palette: BigNumberish[],
      xDim: BigNumberish,
      yDim: BigNumberish,
      svgExtension: string,
      paddingX: BigNumberish,
      paddingY: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string] & { svg: string }>;

    toHexString(
      value: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    toString(value: BigNumberish, overrides?: CallOverrides): Promise<[string]>;

    uri(
      data: string,
      overrides?: CallOverrides
    ): Promise<[string] & { encoded: string }>;

    uriSvg(
      data: string,
      overrides?: CallOverrides
    ): Promise<[string] & { encoded: string }>;
  };

  base64Encode(data: BytesLike, overrides?: CallOverrides): Promise<string>;

  composeLayers(
    layer1: BigNumberish[],
    layer2: BigNumberish[],
    totalPixels: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber[]>;

  composePalettes(
    palette1: BigNumberish[],
    palette2: BigNumberish[],
    colorCount1: BigNumberish,
    colorCount2: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber[]>;

  encodeColorArray(
    colors: BigNumberish[],
    pixelCompression: BigNumberish,
    colorCount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber[]>;

  getColorCount(
    layers: BigNumberish[],
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  render(
    canvas: BigNumberish[],
    palette: BigNumberish[],
    xDim: BigNumberish,
    yDim: BigNumberish,
    svgExtension: string,
    paddingX: BigNumberish,
    paddingY: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  toHexString(value: BigNumberish, overrides?: CallOverrides): Promise<string>;

  toString(value: BigNumberish, overrides?: CallOverrides): Promise<string>;

  uri(data: string, overrides?: CallOverrides): Promise<string>;

  uriSvg(data: string, overrides?: CallOverrides): Promise<string>;

  callStatic: {
    base64Encode(data: BytesLike, overrides?: CallOverrides): Promise<string>;

    composeLayers(
      layer1: BigNumberish[],
      layer2: BigNumberish[],
      totalPixels: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    composePalettes(
      palette1: BigNumberish[],
      palette2: BigNumberish[],
      colorCount1: BigNumberish,
      colorCount2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    encodeColorArray(
      colors: BigNumberish[],
      pixelCompression: BigNumberish,
      colorCount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    getColorCount(
      layers: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    render(
      canvas: BigNumberish[],
      palette: BigNumberish[],
      xDim: BigNumberish,
      yDim: BigNumberish,
      svgExtension: string,
      paddingX: BigNumberish,
      paddingY: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    toHexString(
      value: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    toString(value: BigNumberish, overrides?: CallOverrides): Promise<string>;

    uri(data: string, overrides?: CallOverrides): Promise<string>;

    uriSvg(data: string, overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    base64Encode(
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    composeLayers(
      layer1: BigNumberish[],
      layer2: BigNumberish[],
      totalPixels: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    composePalettes(
      palette1: BigNumberish[],
      palette2: BigNumberish[],
      colorCount1: BigNumberish,
      colorCount2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    encodeColorArray(
      colors: BigNumberish[],
      pixelCompression: BigNumberish,
      colorCount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getColorCount(
      layers: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    render(
      canvas: BigNumberish[],
      palette: BigNumberish[],
      xDim: BigNumberish,
      yDim: BigNumberish,
      svgExtension: string,
      paddingX: BigNumberish,
      paddingY: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    toHexString(
      value: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    toString(
      value: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    uri(data: string, overrides?: CallOverrides): Promise<BigNumber>;

    uriSvg(data: string, overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    base64Encode(
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    composeLayers(
      layer1: BigNumberish[],
      layer2: BigNumberish[],
      totalPixels: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    composePalettes(
      palette1: BigNumberish[],
      palette2: BigNumberish[],
      colorCount1: BigNumberish,
      colorCount2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    encodeColorArray(
      colors: BigNumberish[],
      pixelCompression: BigNumberish,
      colorCount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getColorCount(
      layers: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    render(
      canvas: BigNumberish[],
      palette: BigNumberish[],
      xDim: BigNumberish,
      yDim: BigNumberish,
      svgExtension: string,
      paddingX: BigNumberish,
      paddingY: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    toHexString(
      value: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    toString(
      value: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    uri(data: string, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    uriSvg(
      data: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
